---
- name: install nodejs using nvm
  sudo: yes
  user:
    name: "root"
    password: "{{ 'パスワードを指定'|password_hash('sha512') }}"
  command: bash -c '. ~/.nvm/nvm.sh; nvm install '

# - name: Install Node Module packages
#   sudo: yes
#   sudo_user: ""
#   npm:
#     name: "{{ item }}"
#     global: yes
#     state: latest
#     path: /usr/local/lib/node_modules
#     executable: ~/.nvm/
#   with_items: npm_packages
